warrior/Framework/Utils/data_Utils.py
Issue: Unable to use the environment variable with dots in it
Reason: For ENV substitution, 'get_var_by_string_prefix' method just uses the second part of a string after splitting it using '.'(dot).
Solution:  Use maxsplit argument to get the string comes after first occurrence of '.'(dot).
=> bugfix/WAR-1203: Unable to use the environment variable with dots in it

warrior/WarriorCore/Classes/execution_summary_class.py, warrior/WarriorCore/Classes/html_results_class.py, warrior/WarriorCore/Classes/junit_class.py, warrior/WarriorCore/step_driver.py
Issues fixed here:
1. Case details are not printed as part of Warrior execution summary : added one more condition in 'suite_summary' method to print summary when executing a case
2. Results summary is being printed for case steps : added an optional parameter to print results summary & it should be set to False when called after step execution
How to test - Run any Warrior case and check if the 'Execution Summary' has the status of case in it.
Regression results are in Jira ticket.
=> WAR-1319 : Case details are not printed as part of Warrior execution summary

warrior/Framework/Utils/dict_Utils.py
To handle cases where the /key_value_seperator/ delimiter is also present in the /value/ part of the string.
Cookie is of the format key=value in string type.
but the value has many "=". We convert the string to dict based on delimiter"=" and it fails for all scenarios where we have "=" part of value.
Discussed with developers on possibility of character in value to choose delimiter. Suggestion was to use ":" as delimiter. So i have added a line to replace the 1st occurrence of "=" with ":"
Only The first occurrence is replaced because for cookies we are not expecting multiple values and is always one value.
Tested with users testcase as well as with our own rest tests in DemoTests.
Demo test results and regression results are available in the jira ticket.
=> WAR-1150: improve convert_string_dict function 

warrior/Framework/Utils/data_Utils.py
Current behaviour : 
If we have two ENV variable defined "<url>{ENV.IPADD}:8443//${ENV.R_NODEID}</url>". While replacing the first variable IPADD the replace function changes the string to unicode as the value is pulled from JSON ENV_variable file. But only string are accepted in the current code. So whenever we have more than one ENV or REPO variables defined and if the value of anyof these variables is unicode. The second substitution does not happen. Unicode values are introduced whenever we load the values for the variables from any json files. 
Change : Adding "unicode" type along with string.
=> war 1297: Env Variable keyword not working for URL that has more than one

warrior/WarriorCore/framework_detail.py
No specific Tests required for the pull request.
Current change is adding the Python version in logs to inform/help users know the underlying python version. This is important when users try to replicate the same results under different environment. It is important to factor the python version too, while trying to replicate same results across platforms. 
The bold one below is the new addition
======================== WARRIOR FRAMEWORK DETAILS ========================== 
-I- The Warrior framework used is /home/hsudarsa/github/python_version/warriorframework
-I- The Warrior framework Release is Ninja
-I- The Warrior framework version is warrior-3.2.0
**-I- The Warrior framework is running on python version 2.7.12**
======================== WARRIOR FRAMEWORK DETAILS …
=> WAR-1003: Adding python version details alongside warrior details

wftests/ci/pylint.sh
The change is for ignoring the the files deleted in the PR target branch during pylint check
Adding 'diff-filter=d' option in the git command(we use to get the diff files) will ignore the deleted files.
=> WAR-1405 : Travis- Ignore deleted files for pylint check

warrior/WarriorCore/testcase_driver.py
Code change(s): Print the value provided in the 'Expected Results' field of a testcase during execution.
How to test: Run any test to see if the value provided in the 'Expected Results' field is being printed in the console along with other testcase details.
Logs: Regression logs are attached in the Jira ticket
=> WAR-1450: Print the 'expected result' before the test case starts

warrior/Framework/ClassUtils/configuration_element_class.py
Change the function to expand variable to use a simplified logic
Make sure it only perform an expand/replace when there is a match
Test is added in internal repo
=> WAR-1494 Variable substitution process string incorrectly when string doesn't contain end_pattern longer than 1 char

warrior/Framework/Utils/data_Utils.py
Code change: Support variable substitution for sys tag in td file
Logs and test instructions in the Jira ticket.
=> WAR-1451: Need variable substitution for sys in test data

warrior/Framework/ClassUtils/WNetwork/warrior_cli_class.py
failure in variable substitution in testdatafile does not result in ERROR status for the step.
=> war-1507: result from _get_response_dict is not combined properly with the result from _send_command_retrials

wftests/ci/pylint.sh
Add check for skipping master branch protection for branch name starts with release
=> fix release branch falsely trigger pylint failure

warrior/Framework/Utils/email_utils.py, warrior/Tools/w_settings.xml
Add a support to send warrior notification emails to multiple receivers - when comma separated value is given w_settings file.
Logs and test instructions in the jira ticket.
=> WAR-1575: As a user, I need a support to send emails to multiple receivers

warrior/WarriorCore/Classes/warmock_class.py
Add a commands block that can contain different command response text block, referenced by cmd text
The order of finding response match is:
cmd specific response with simresp > global response with simresp > cmd specific response default > global response default
A manual verification test has been appended into the same warmock testcase in internal repo
=> WAR-1542 Support command specific responses for warmock

warhorn/source/utils.py, warhorn/warhorn.py
giving commit id in label tag for warhorn configuration was not working like giving proper branch name. Check giving commit id and warhorn pulls the right files.
=> bugfix/WAR-1609-new: resolved commit-id not working in label tag

warrior/Framework/ClassUtils/netconf_utils_class.py
Issue: Due to the changes in #92, netconf.connect returns None when authentication fails during connection establishment and this needs to be handled in the calling method(s).
Fix: Return False if connection fails in the 'open' method of 'netconf_utils_class.py'
How to test: Run any netconf tests(conenct_netconf kw is enough) with wrong password in the data file. connect_netconf kw was throwing exception earlier, now it is handled correctly and the kw status will be set to False.
=> WAR-1680 : Using context as negative in connect_netconf keyword is giving EXCEPTION error

warrior/WarriorCore/iterative_parallel_testcase_driver.py, warrior/WarriorCore/sequential_testcase_driver.py
Issue - Duplicate entries in the execution summary when executing 'iterative_parallel' suite.
Reason - Same junit object is being added multiple times to the multiprocessing queue during 'iterative_parallel' suite execution.
Fix - junit_object/python_process is same for all the cases executed in the same system for 'iterative_parallel' suite execution so do not append junit object into queue for all the cases(just add once).  Code changes are in 5a83b8c, rest are pylint fixes.
How to test - Run any suite with exectype as 'ITERATIVE_PARALLEL' with more than one system in a data_file(test use-case and regression results are in the jira ticket).
=> WAR:1583 - Incorrect Results printed on Console window for iterative Parallel TC

.travis.yml, warrior/Actions/SeleniumActions/browser_actions.py, warrior/Framework/ClassUtils/WSelenium/browser_mgmt.py, warrior/Framework/Utils/selenium_Utils.py, warrior/Warrior, warrior/WarriorCore/Classes/war_cli_class.py, warrior/WarriorCore/warrior_cli_driver.py, wftests/warrior_tests/data/selenium_func_tests/data_selenium_headless.xml, wftests/warrior_tests/testcases/selenium_tests/tc_selenium_headless.xml
Due to #62 and #133 changes which cause instability to the platform as the code logic is flawed
This PR revert those changes and will provide a stable release
This ticket also includes changes for WAR-1591
and necessary support for WAR-1074 to run correctly
With firefox version 47 and above, a geckodriver is needed in the local sys env path
https://github.com/mozilla/geckodriver/releases
Chrome needs chromedriver
https://sites.google.com/a/chromium.org/chromedriver/downloads
if geckodriver is needed, then selenium version needs to be 3.5 or above
https://github.com/mozilla/geckodriver#selenium
which means for Firefox 47 and above, warrior needs both geckodriver and selenium >= 3.5 to run
Chrome isn't affected
For geckodriver launched firefox
currently found that browser.capabilities dict …
=> WAR-1548 Refactor selenium keyword to support both selenium 2.0 and 3.0 with different version of chrome/firefox

warrior/Framework/ClassUtils/netconf.py
Issue description:
User provides xpath 'filter_string' value in testcase as an argument for netconf keywords. It can have a single or double quotes in it, there are two ways to represent it in xml(tc):
1. If xpath filter_string has single quotes in it then it has be wrapped inside double quotes
`Ex. <argument name="filter_string" value="/snmp/trap-group[contains(trap-group-name,'testing1')]"/>`
2. If xpath filter_string has double quotes in it then it has be wrapped inside single quotes
`Ex. <argument name="filter_string" value='/snmp/trap-group[contains(trap-group-name,"testing1")]'/>`
Warrior constructs XML request_string(to be sent to netconf interface) using filter_type and filter_string values in 'netconf.py: get' util method. Since the incoming filter_string can have single or …
=> WAR-1683(develop): NETCONF get function is not working with xpath

warrior/WarriorCore/Classes/html_results_class.py, warrior/WarriorCore/Classes/junit_class.py, warrior/WarriorCore/project_driver.py, warrior/WarriorCore/testcase_driver.py, warrior/WarriorCore/testsuite_driver.py
Requirement : 
User requires the HTML file link while starting the Project/Suite/Case. So that he/she could do real time monitoring during execution.
Fix Explanation: 
Made the Result summary file(HTML file link) to get printed only at the beginning and end of the execution and removed the same(Result summary file) which was earlier printed at the end of each step.
Attached the regression logs and added the instruction for testing in JIRA.
=> WAR-1685 : Need Result HTML link during the start of execution

warrior/Framework/Utils/email_utils.py, warrior/WarriorCore/Classes/execution_summary_class.py
Requirement : Add 'execution summary' in email sent by WF along with (i) Project/Suite/Case path , (ii) Logs directory & (iii) Result directory
Fix explanation :
Modified project_summary & suite_summary methods to return the execution summary prints(which were printed inside these methods earlier, now it will be printed in print_result_in_console method)
Added 'construct_mail_body' method to format execution summary in html format that would be added in email
Earlier the mail body was in 'plain text' format, now changed it to 'html' for better formatting of mail body
Attached the regression logs and added the instruction for testing in JIRA.
=> WAR-1717:Need snapshot of Result Summary within the mail

warrior/Warrior, warrior/WarriorCore/testcase_driver.py
Use the following command (in 1 line) to test
`python warrior/Warrior -datafile wftests/warrior_tests/data/rest_functional_tests/rest_verify_response_data.xml wftests/warrior_tests/testcases/rest_functional_tests/tc_rest_verify_content_response.xml wftests/warrior_tests/testcases/rest_functional_tests/tc_rest_verify_response.xml`
=> WAR-1687 (develop) : Execute multiple test cases via command line by specifying input data file - bugfix

warrior/Actions/CommonActions/common_actions.py, warrior/Warriorspace/Config_files/Samples/Set_REPO_Variable_Sample.json, wftests/warrior_tests/testcases/common_actions_tests/verify_data_test.xml
Requirement is to support storing multiple values in data_repository using 'store_in_repo' kw by passing a file.
Similar support is already available in set_env_var kw by passing json file, same logic is used here.
Test instructions & Regression results are available in Jira ticket
=> WAR-1679: In store_in_repo  keyword user was allowed to update only variable at a time, it should allow to update n number of variable

.travis.yml, warrior/WarriorCore/iterative_parallel_testcase_driver.py, warrior/WarriorCore/multiprocessing_utils.py, warrior/WarriorCore/parallel_testcase_driver.py, wftests/warrior_tests/data/framework_tests/data_exec_summary.xml, wftests/warrior_tests/projects/pj_exec_summary.xml, wftests/warrior_tests/suites/framework_tests/exec_summary/ts_parallel_tcs.xml, wftests/warrior_tests/suites/framework_tests/exec_summary/ts_sequential_tcs.xml, wftests/warrior_tests/testcases/framework_tests/exec_summary/tc_custom.xml, wftests/warrior_tests/testcases/framework_tests/exec_summary/tc_iterative.xml
Expectations of Parallel testcases execution,
1. Separate child process will be created for executing each testcase and copy of master junit object will be sent across all processes.
2. Each process will add the result in the corresponding junit object.
3. After the completion of all processes, those junit objects will be collected to fetch all the newly added results.
4. Warrior will add those results into the original master junit object.
Issue: Filtration is not happening at step3, Warrior adds all the existing results into original master junit object.
Solution: Use Testsuite timestamp to filter out the newly added results so that there will not be any duplicate entries.
Test instructions and regression logs are in Jira ticket.
=> WAR-1694(develop): Project with parallel suite(s) creates duplicate entries in execution summary

warrior/WarriorCore/Classes/testcase_utils_class.py
Issue: 
------
Two print messages being logged in case of a print_warning(). 
Fix:
---
- The print_warning() calls print_main() which has a call to p_note_level()(WarriorCore/Classes/testcase_utils_class.py).
- p_note_level() maintains a print_util_types [] list, which has the supported print_types.
- The print_util_types [] list currently holds only white color code for warning ['-W-'].  
- As warning message is printed in different color, added the -W- type with its color coding ["\033[1;33m-W-\033[0m"] to the print_util_types [] list in the p_note_level () method.
Added the logs in JIRA
=> WAR-1358: print_warning creates two print 1. -W- "Warning 2. -I- Information

warrior/Framework/ClassUtils/WNetwork/warrior_cli_class.py
Requirement:
Response of the keyword 'send_commands_by_testdata_title_rownum' keyword should be stored in data repository.This was working as expected till warrior-3.4.0.
Reason for the issue:
In _get_response_dict method (Framework/ClassUtils/WNetwork/warrior_cli_class.py), for the condition, resp_pat_req is None, empty string is provided as value for ' resp_ref ' key.
Fix Explanation:
Replaced the empty string which was provided as value for ' resp_ref ' key with the response value.
Attached the regression logs and instructions for testing in Jira.
=> WAR-1802 : The keyword 'send_commands_by_testdata_title_rownum' does not store the response into the data repository

warrior/WarriorCore/testsuite_driver.py
Issue:
- Datafile provided in cmd line should take precedence over the file given at the suite level which is not happening for iterative(parallel/sequential) execution.
- In IterativeTestsuite class(iterative_testsuite_class.py) constructor method, we use the datafile given in 
y) constructor method, we use the datafile given in the suite file for getting the list of systems for iteration instead of the one given at cmd line.
Fix:
- First priority is given for data files specified via CLI
- Default datafiles are the ones specified in the test suite globally.
- If no datafiles are specified at CLI or global level, error is thrown.
- At Suite level execution, step-wise datafiles are not considered.
Testcase validation:
- Verified the fix with the sequential suite: …
=> WAR-1381: Not getting executed for y number of systems specified in ID file (when ID is passed using CLI command)

warrior/Framework/ClassUtils/json_utils_class.py, wftests/warrior_tests/config_files/rest_functional_tests/verify_api_response.json, wftests/warrior_tests/testcases/rest_functional_tests/tc_rest_verify_content_response.xml
Issue : 
1. In strip() method,the characters in the specified string(the string that needs to be removed) will be stripped from both the ends of the string. 
2. In compare_json_using_jsonpath method (json_utils_class), the strip() method provided to remove 'jsonpath=', also removes characters in trailing end of string, if it finds the same characters as in 'jsonpath='.
(i.e) strip('jsonpath=') in "jsonpath=admin-status" gives the result as 'dmin-statu' instead of admin-status.
This resulted in an error "doesn't match or available in the actual response value None", as the key is not present
Fix Explanation:
1. Replaced the strip(string) with strip().replace(string, '')
Added the regression logs and instructions for testing in Jira.
=> WAR-1843 : verify_response keyword in rest failing even for correct jsonpath

.travis.yml, warrior/Actions/SeleniumActions/browser_actions.py, warrior/Framework/ClassUtils/WSelenium/browser_mgmt.py
Issue:
-------
_makebrowser method has profile_dir as well as **kw_args. However, profile_dir value is obtained from kw_args in previous step. Due to this, now there are two profile_dir attributes in __make_browser function call. This results in above failure.
TypeError: _make_browser() got multiple values for keyword argument 'profile_dir'
**Fix:**  Added logic to remove the profile_dir from kwargs, if exists.
Other Issues fixed along with this are:
Issue-1: 
-------
Binary, gecko_path, gecko_log, proxy_ip, proxy_port values given through datafile where not being read in browser_actions.
**Fix:**  Appended the default argument dict with these attributes. Now, the values are being read from the datafile.
Issue-2:
--------
gecko-log specified in datafile was not being read correctly in …
=> WAR-1813: Selenium: _make_browser() function got multiple values for keyword argument 'profile_dir'

wftests/warrior_tests/config_files/rest_functional_tests/verify_api_response.json
Issue:
Rest testcases have been failing due to the volatility of httpbin server.
Fix:
The failure is because of the Content-Length variation in get method(httpbin server). Thus, content-length verification fails. By changing the value to the expected content-length in the json file used for verification, this failure can be fixed.
Attached the regression logs in Jira.
=> WAR-1990: Temporary fix in rest cases to avoid Travis/Jenkins failure

warrior/Framework/Utils/data_Utils.py, warrior/Warrior, warrior/WarriorCore/Classes/war_cli_class.py, warrior/WarriorCore/warrior_cli_driver.py
Issue:
------
cse script execution is not supported in warriorframework repo(OSS) as it is internal to FNC, action file has been removed already but the Warrior executable(function call) & parser methods still has some cse code which needs to be removed. cse option should not be listed in warrior help as well.
Fix:
---
Removed all the cse related code from warriorframework.
Removed from help options as well.
Related logs are attached in JIRA: WAR-1116
=> WAR-1116: Remove 'cse script execution' option from warriorframework repo

warrior/Framework/ClassUtils/WNetwork/warrior_cli_class.py
Existing issue:
1. In connect and send keywords, we use pexpect.TIMEOUT to handle timeout exceptions. But this is not supported for versions of pexpect > = 4.0, in which pexpect.TIMEOUT is replaced with pexpect.exceptions.TIMEOUT
2. If the session timed out because of invalid prompt or if the prompt is not received even after 60 sec wait,  the exception(<class 'pexpect.exceptions.TIMEOUT'>) is raised which gets converted to string and added with the response.
Fix Explanation:
1. Removed the timeout exception string from the response, which gets added to response when the prompt is not received.
2. Included an error message, to indicate the user that the command has timed out.
Adding regression logs and instructions for testing in Jira.
=> WAR-1840 : Handle session timeout changes in pexpect 4.x for connect/send keywords

warhorn/default_config.xml, warhorn/source/utils.py, warhorn/user_generated/config_sample.xml, warhorn/warhorn.py
Added an option to provide username and password in warhorn config file to support cloning private repositories(applicable to http/https url types).
For http/https url types, given username and password will be added to the git url to support cloning repo at command line itself.
How to test: Clone private(http/https) driver/warriorspace/tools repo by providing username & password in corresponding block in warhorn config file. Sample config file and the combinations tested are in Jira ticket.
=> WAR-1650: Need to change the way warhorn clones repositories in order to support cloning private repositories

.travis.yml, warrior/WarriorCore/Classes/iterative_testsuite_class.py, warrior/WarriorCore/Classes/junit_class.py, warrior/WarriorCore/parallel_testcase_driver.py, warrior/WarriorCore/sequential_testcase_driver.py, warrior/WarriorCore/sequential_testsuite_driver.py, wftests/warrior_tests/config_files/selenium_func_tests/ec_verify_presence_of_elements.json, wftests/warrior_tests/config_files/selenium_func_tests/ec_warrior_selenium_Config.json, wftests/warrior_tests/projects/pj_framework_tests.xml, wftests/warrior_tests/projects/selenium_project.xml, wftests/warrior_tests/suites/framework_tests/invalid_path_tests/ts_iter_par.xml, wftests/warrior_tests/suites/framework_tests/invalid_path_tests/ts_iter_seq.xml, wftests/warrior_tests/suites/framework_tests/invalid_path_tests/ts_parallel.xml, wftests/warrior_tests/suites/framework_tests/invalid_path_tests/ts_sequential.xml
Issue:
------
TestSuite end results are printed as Passed/Failed for an invalid test case path.
Expected Behavior:
---------------------
TestSuite results ahould be displayed as 'ERROR' on executing a test case with an invalid path for all testcase types:
1. sequential testcases 
2. parallel testcases
3. iterative parallel
4. iterative sequential
Fix:
---
1. Initialized timestamp for testcase[wt_tc_timestamp] and testsuite[wt_ts_timestamp] to 'None' in testcase and testsuite driver files respectively as these details do not get updated on testcase/testsuite path failure cases which in turn was throwing 'keyError'.
2. Defaulting timestamp attribute as 'None' in update_attr in junit_class file.
3. Setting the testsuite status as 'Error' if error value is received in iterative testsuite …
=> WAR-1828: Testsuite end result printed as PASS eventhough the testcase in that suite is not in provided path

warrior/WarriorCore/common_execution_utils.py, warrior/WarriorCore/project_driver.py, warrior/WarriorCore/sequential_testcase_driver.py, warrior/WarriorCore/sequential_testsuite_driver.py, warrior/WarriorCore/step_driver.py, warrior/WarriorCore/testcase_driver.py, warrior/WarriorCore/testcase_steps_execution.py, warrior/WarriorCore/testsuite_driver.py
Requirement:
1. Currently, if a step/testcase passes all the attempts and if it was set to "RUF", no print messages specifying the end of attempts is given out on the console. A message at the point where those attempts finish would be helpful to the person reading the logs later.
Fix Explanation:
1. Included the print statements at the beginning and end of runmode execution as an indication to user that the runmode execution completed all the provided attempts. 
Added the regression logs and instructions for testing in Jira.
=> WAR-542: As a user, I want to know if a step/testcase passed all attempts when that it was set to RUF & RUP
