wftests/ci/pylint.sh

All pylint job should compare to develop
As develop will be the latest branch for development

Change pylint diff branch from master to develop

---

katana/static/app/controllers/newTestDataFileCtrl.js
katana/static/app/partials/newtestdatafile.tmpl.html
katana/static/css/style.css

bug fixes for cli data page
also includes changes from WAR-1259 katana: fix Iter Type value

Feature/war 1260: Katana: Add bypassed checks in testdata files back into the testdata controller	

---

warrior/WarriorCore/Classes/execution_summary_class.py

Execution summary is not getting printed correctly at the end of warrior execution if we have the same suite "n" number of times in a project file

WAR-1037 : Execution summary is not getting printed correctly at the end of warrior execution

---

wftests/ci/pylint.sh

The original pull request contains change that makes pylint fail on multiple files change condition, adding double quote to the file list argument fix the problem

Feature/war-1188 Pylint fix

---

warrior/Actions/CliActions/cli_actions.py
warrior/Framework/ClassUtils/WNetwork/diagnostics.py
warrior/Framework/ClassUtils/WNetwork/file_ops.py

Code changes:
1. Modify send_command keyword to use new WarriorConnect class
2. Modify utils methods in diagnostics.py & file_ops.py to use new WarriorConnect class(raised backlog ticket)
How to test:
Run warrior_tests/testcases/cli_tests/other_attr/tc_send_command.xml - to test cli send_command kw
Tests for 'NetworkActions/FileOps' keywords will be added as part of WAR-1339.
Regression results are in WAR-1323 Jira.

WAR-1323: Modify send_command(cli) keyword to use new WarriorConnect class

---

warrior/WarriorCore/step_driver.py

Fixedcode that caused duplicate step entries in junit file and hence the html file.

WAR-1357: fixed code causing duplicate step entries in the junit

---

wftests/ci/pylint.sh

For pull request that doesn't merged into develop
this solve the problem of forced testing on develop for the pull request
Please don't delete the branch until it is also merged into katana-develop
@sanikakulkarni please merge this branch into katana-develop once this is approve

WAR-1368 update develop into travis target branch

---

katana/native/settings/settings.py
katana/native/settings/static/settings/js/settings.js
katana/native/settings/templates/settings/email_setting_handler.html
katana/native/settings/templates/settings/general.html
katana/native/settings/templates/settings/index.html
katana/native/settings/templates/settings/jira_setting_handler.html
katana/native/settings/templates/settings/secret.html
katana/native/settings/urls.py
katana/native/settings/views.py
katana/utils/directory_traversal_utils.py
katana/utils/navigator_util.py
katana/wui/core/core_utils/apps_class.py
katana/wui/core/core_utils/core_index_class_utils.py
katana/wui/core/static/core/css/main.css
katana/wui/core/static/core/js/main.js
katana/wui/core/templates/core/index.html

War 1238 - core changes and settings app

---

katana/native/settings/static/settings/js/settings.js
katana/native/settings/templates/settings/jira_setting_handler.html
katana/wui/core/static/core/css/main.css
katana/wui/core/static/core/js/main.js
katana/wui/core/templates/core/index.html

*Finished Jira Settings
*Added Dialog Box
*Fixed bootstrap .row css conflict
*Added loading spinner
*Added new Font

War 1238 bugfixes and updates

---

katana/wui/core/static/core/js/main.js

add animation support into main js

---

warrior/Tools/w_settings.xml
warrior/WarriorCore/Classes/war_cli_class.py
warrior/WarriorCore/warrior_cli_driver.py

Moved the hardcoded jobid urls out of the repo
Users can assign jobid url in tools and trigger it by passing the id with -jobid argument in cli
example result in jira

WAR-1142 remove url from code and add logic to read url from w_settings

---

warrior/Actions/NetconfActions/netconf_Actions.py
warrior/Framework/ClassUtils/netconf.py
warrior/Framework/ClassUtils/netconf_utils_class.py

WAR-1296: supports netconf protocol version 1.1
and add get-schema and cancel-commit
WAR-1137: add clear notification buffer
WAR-1138: add print notification buffer

WAR-1296:update netconf related files

---

katana/wui/core/static/core/js/main.js

use katana.templateAPI.postTabRequest(tabTitle, url, input_data, **other_args) to spawn a new app in a new tab

WAR-1425 Open app in new tab using POST request

---

katana/native/wdf_edit/templates/wdf_edit/index.html

Change the text submit to save

WAR-1329 WDF Editor minor text fix

---

warrior/Warrior
wftests/ci/pylint.sh

CI test done
Refer to https://travis-ci.org/warriorframework/warriorframework/builds/279566939 for master branch trigger

Bugfix/WAR-1426 Fix skipped Warrior executable scan and check merge to master

---

katana/katana.py
katana/static/app/controllers/newProjectCtrl.js
katana/static/app/controllers/newTestsuiteCtrl.js
katana/static/app/controllers/projectCaptureCtrl.js
katana/static/app/controllers/testcaseCapCtrl.js
katana/static/app/controllers/testsuiteCapCtrl.js
katana/static/app/factory/fileFactory.js
katana/static/app/partials/newproject.tmpl.html
katana/static/app/partials/newtestsuite.tmpl.html
katana/static/app/partials/projectcapture.tmpl.html
katana/static/app/partials/testcasecapture.tmpl.html
katana/static/app/partials/testsuitecapture.tmpl.html

Dynamically formed links of Testcase(from Suite) could be opened in Linux as well as Windows.

WAR-1340 : Links to open Testcase from Suite

---

katana/native/wdf_edit/static/wdf_edit/js/main.js
katana/native/wdf_edit/templates/wdf_edit/failure.html
katana/native/wdf_edit/views.py
katana/wui/core/static/core/css/main.css

add error page for non-exist xml 
fix css button for wdf editor
handle empty value peacefully

WAR-1329 Small enhancements for wdf-editor

---

warrior/Framework/ClassUtils/configuration_element_class.py
warrior/Framework/Utils/data_Utils.py

Support using data_repo values in IDF & VC files
Logs and test instructions in the Jira ticket.

WAR-1168: Option to use data repository values in Input Data and Var config files

---

katana/static/app/controllers/newTestsuiteCtrl.js
katana/static/app/controllers/testsuiteCapCtrl.js
katana/static/app/partials/newtestsuite.tmpl.html
katana/static/app/partials/testsuitecapture.tmpl.html
katana/tooltip/testsuite_tooltip.json

Testcase could be inserted while Creating/Editing a Suite.

WAR-1311 : Way to insert Testcase in Suite

---

warrior/Actions/CommonActions/common_actions.py

As a user I want options in set env KW. 
Option is to chose from terminal if it is available.

WAR-1447 : Adding option in set env kw to choose from terminal too

---

warrior/Actions/CommonActions/common_actions.py

Reminding user during Warrior wait for time out.

WAR-1446: As a user, I want to see wait time on screen

---

warrior/Actions/SnmpActions/common_snmp_actions.py
warrior/Framework/ClassUtils/snmp_utlity_class.py
warrior/Framework/Utils/snmp_utils.py

1. SNMP Keyword exception Handle update.
2. verify_snmp_action keyword updated with OID Mib translation.
3.Testing and Verification with PYSNMP-4.3.8
4. SUPWAR-130 Fixed.
5. SUPWAR-156 Fixed.
6. For snmpbulkget non-repeaters, and max-repeaters user configurable attribute added.

WAR-1256-Exception-Handling-and-verify_snmp_action-Keyword-Update

---

warrior/Framework/Utils/xml_Utils.py
warrior/WarriorCore/testcase_driver.py

Requirement : More user friendly print statements when there are issues with case/suite/project xml files
Additionally added : Input data file which is embedded to testcase, suite. 
To Test : 
1. Execute a malformed xml case/suite/project   
2. Execute a test with datafile which is malformed

War 1152 : Handle errors when Testcase, Project, Suites & Input Data file are not well formed.

---

warrior/Framework/ClassUtils/configuration_element_class.py

Regression passed except for hybrid (WAR-1479)
Tests are also updated in internal repo for more coverage in different pattern

WAR-1494 fix regex pattern for repetitive pattern 

---

warrior/WarriorCore/Classes/hybrid_driver_class.py
warrior/WarriorCore/exec_type_driver.py

Add exec_type_driver to hybrid driver
so it can process rules in execute tag first before step execution
Test log are attached in Jira

WAR-1479 Support multiple rules/exectypes for hybrid mode

---

warrior/Framework/ClassUtils/WNetwork/warrior_cli_class.py
warrior/Framework/Utils/data_Utils.py

Added documentation for the code done in war-1156.

bugfix/WAR-1514: added documentation to the code done in war-1156

---

AUTHORS

Refer to the WAR ticket for details of contribution. This could be part of the upcoming release.

War 1552- Add new authors, whose contribution would be available in the upcoming release. 

---

CONTRIBUTING.md
release_notes.txt
version.txt

Pylint error is caused by code skipped pylint, ticket created (WAR-1560)

Merge release note back to develop

---

katana/static/app/controllers/testcaseCapCtrl.js
katana/static/app/partials/testcasecapture.tmpl.html
katana/tooltip/testcase_tooltip.json

Testcase  --> Step --> Execute Type : 
>For the Execute Type 'If' & 'If Not', Multiple conditional statements are supported.
>Operator has been added for each rule which is an optional field.
>Top level Else & Else Value for the Execute Type in case the expression fails.
>User provided Expression field for the logical operations among the rules.

WAR-912 : Multiple conditional statements for Execute Type

---

warrior/Tools/reporting/html_results_template.html
warrior/WarriorCore/Classes/html_results_class.py
warrior/WarriorCore/framework_detail.py

User Details has been added in CLI & HTML Result Summary.

WAR-1576 : User details in CLI & HTML Result Summary

---

warrior/Tools/reporting/html_results_template.html
warrior/WarriorCore/Classes/html_results_class.py

Step Description added to HTML Result summary Page

WAR-1568 : Step Description in HTML Result summary Page

---

warrior/Framework/ClassUtils/configuration_element_class.py
warrior/Framework/ClassUtils/testdata_class.py

If list is given in per_td_block, then it should be iterated.
Currently all values in list will be printed next to next.
Test is added to warrior_fnc_test

WAR-1445: Iteration by test block not working for list

---

warrior/Framework/Utils/data_Utils.py

Altered the print statements in the way user can understand and verified with the reporter.
Regression results and sample test are added to the ticket

WAR-1630: Unable to know whether the pattern match is failed due to software or an expected failure  from the script

---

katana/utils/json_utils.py
katana/wapps/wdf_edit/static/wdf_edit/js/main.js
katana/wapps/wdf_edit/templates/wdf_edit/editor/child_tag_editor.html
katana/wapps/wdf_edit/templates/wdf_edit/editor/subsys_editor.html
katana/wapps/wdf_edit/views.py

Need to display both tags correctly
and if the values of those tags also have multiple tags with same name
need to display those correctly also!!!
AND
when it is sent back to the server the logic also needs to be modified!!!

WAR-1713 WDF editor needs to show tag/value correctly if both tag has the same name

---

warrior/Actions/CommonActions/common_actions.py
warrior/Framework/Utils/data_Utils.py
wftests/warrior_tests/suites/common_action_tests/common_action_suite.xml
wftests/warrior_tests/testcases/common_actions_tests/tc_verify_arith_exp.xml
wftests/warrior_tests/testcases/common_actions_tests/verify_data_test.xml

1. Add a keyword to evaluate arithmetic operations and to compare the expression output with the expected value
2. Add a logic to fetch nested key values in get_object_from_datarepository method
Logs and test instructions in the Jira ticket

WAR-1478: Arithmetic operation support for response patterns stored through resp_ref and also in verify tags

---

katana/wui/core/static/core/css/main.css
katana/wui/core/static/core/js/main.js
katana/wui/core/templates/core/index.html
katana/wui/core/templates/core/landing_page.html

added apps drag and drop as well as katana-rclick attribute which triggers a method when the attribute is present and element is clicked using a right click like katana-click, however needs design meeting to discuss where to save order. for now changes will only appear per instance but will create a ticket for saving order for next reload.

WAR-1404: added apps drag and drop

---

katana/wui/core/static/core/css/main.css
katana/wui/core/static/core/js/main.js

https://github.com/warriorframework/warriorframework/wiki/Warrior-UI-Documentation#validationapi

Form validation added

---

.travis.yml
warrior/Actions/SnmpActions/common_snmp_actions.py
wftests/ci/pylint.sh

instead of simple text matching, support regex using the re library in python

WAR-1760 support regex in snmp verify keyword

---

warrior/WarriorCore/Classes/war_print_class.py

1. Write console log correctly to the livehtmlobj
2. Handle normal warrior execution when livehtmlobj is not present
Normal execution can be tested by running any of the testcase in wftests
eg. testcases/framework_tests/cond_var/pass.xml
console log is verified manually while developing internal app

WAR-1744 & WAR-1743 katana livehtmlobj update

---

warrior/Actions/CommonActions/common_actions.py
wftests/warrior_tests/suites/common_action_tests/common_action_suite.xml
wftests/warrior_tests/testcases/common_actions_tests/repo_variables.json
wftests/warrior_tests/testcases/common_actions_tests/tc_store_in_repo.xml

Fix for WAR-2039 Nested Dict is not handled in store_in_repo function

---

warrior/WarriorCore/sequential_testcase_driver.py
wftests/warrior_tests/projects/pj_framework_tests.xml
wftests/warrior_tests/suites/framework_tests/on_error_goto/ts_with_on_error_goto_sc1.xml
wftests/warrior_tests/suites/framework_tests/on_error_goto/ts_with_on_error_goto_sc2.xml
wftests/warrior_tests/testcases/framework_tests/on_error_goto/tc_on_error_goto_sc1.xml
wftests/warrior_tests/testcases/framework_tests/on_error_goto/tc_on_error_goto_sc2.xml

Feature/war 1978(The onError_action does not work when implemented in Test Suite)

---

katana/static/app/controllers/testcaseCapCtrl.js
katana/static/app/partials/testcasecapture.tmpl.html

fix for war-1773(Goto does not calculate step numbers correctly when runmode and/or retry is included in steps)

---

warrior/Tools/reporting/html_results_template.html
warrior/WarriorCore/Classes/execution_files_class.py
warrior/WarriorCore/Classes/execution_summary_class.py
warrior/WarriorCore/Classes/html_results_class.py
warrior/WarriorCore/Classes/junit_class.py
warrior/WarriorCore/Classes/testcase_utils_class.py
warrior/WarriorCore/Classes/war_cli_class.py
warrior/WarriorCore/step_driver.py
warrior/WarriorCore/testcase_driver.py
warrior/WarriorCore/testsuite_driver.py
warrior/WarriorCore/warrior_cli_driver.py
wftests/warrior_tests/wrapper_files/tw_sample.xml

WAR-2041 - common setup and common cleanup cli changes

---

setup.py

- Attached the regression logs in Jira.

Feature/war 2091(Warrior Core: To address Security Vulnerability in python packages.)

---

warrior/WarriorCore/testcase_driver.py
wftests/warrior_tests/suites/common_action_tests/ts_common_action_suite_wrapper.xml
wftests/warrior_tests/testcases/common_actions_tests/tc_store_in_repo_wrapper.xml
wftests/warrior_tests/wrapper_files/common_actions_tests/tw_store_in_repo.xml

WAR-2098 fix for getting relative paths from wrapper file

---

warrior/Actions/SnmpActions/common_snmp_actions.py
warrior/Framework/ClassUtils/snmp_utlity_class.py
warrior/Framework/Utils/snmp_utils.py

SNMP: start trap listener key word is not working properly when running the Suite file

WAR-2097 : SNMP: start trap listener key word is not working properly when running the Suite file

---

warrior/WarriorCore/Classes/warmock_class.py

add log="true" argument in verify_cmd_response in warmock_class

WAR-2140 - update warmock_class.py

---

release_notes.txt
version.txt

WAR -2139 : Warrior Release 3.12.0  PR to merge release branch to the develop.

Warrior FrameWork Release - 3.12.0

---

release_notes.txt
version.txt

PR: To merge to the develop branch.

Warrior FrameWork Release - 3.12.1 - Hotfix Release.

---

release_notes.txt
version.txt

PR to Merge to the Master Branch

Release warrior 3.12.1

---

warrior/Framework/ClassUtils/rest_utils_class.py
wftests/warrior_tests/config_files/rest_functional_tests/verify_api_response_with_repo_variable.json
wftests/warrior_tests/data/rest_functional_tests/rest_verify_response_data.xml
wftests/warrior_tests/suites/rest_functional_tests/rest_json_test_Suite.xml
wftests/warrior_tests/testcases/rest_functional_tests/tc_not_presented_repo_variable_substitution_in_verify_response.xml
wftests/warrior_tests/testcases/rest_functional_tests/tc_repo_variable_substitution_in_verify_response.xml

Attached the pass logs in jira

fix for war-2134(Adding support for REPO substitutions as well in verify response json)

---

warrior/Framework/ClassUtils/WNetwork/warrior_cli_class.py

Feature/war 1686(No need to wait for sleep timer during mockrun)
